name: Daily Subreddit Tracker

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz praw


      - name: Run the tracker script
        run: python scripts/new-reddit-community.py

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: subreddit-results
          path: results/
